theme: jekyll-theme-minimal
author: Pedro Perez-Murueta
logo: images/pedro.jpg
title: Welcome to the Manchas2k4's homepage!
description: In this site you will find tutorials on the installation of the various tools that I use in my courses.
